config/routes.rb
Rails.application.routes.draw do

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'sessions/new'
  resources :posts
  resources :users

  resources :posts do 
    member do 
      put 'like' => "posts#like"
      put 'dislike' => "posts#dislike"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :User
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :dislike]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @users = User.all
  end

  # GET /posts/1/edit
  def edit
    @users = User.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @users = User.all
    @post.User_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @post.like_from current_user
    redirect_to posts_path
  end

  def dislike
    @post.disliked_by current_user
    redirect_to posts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:conteudo, :User_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_field :conteudo, value: "253" %>
  </div>

    <% if current_user %>
        User ID:<%= current_user.id %>
        User Name: <%= current_user.nome %>
        <%= form.hidden_field :user_id, value: current_user.id%>
    <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Conteudo</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <%if post.User.id != current_user.id %>
      <tr>
        <td><%= post.conteudo %></td>
        <td><%= post.User.nome.capitalize %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.User.id == current_user.id%>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>

        <td><%= link_to like_post_path(post), class: "like", method: :put do%>
          <button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-thumbs-up"> <%=post.get_likes.size%></span> Likes
          </button>
        <%end%></td>

        <td><%= link_to dislike_post_path(post), class: "like", method: :put do%>
          <button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-thumbs-down"> <%=post.get_dislikes.size%></span> Dislikes
        </button>
        <%end%></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/perfil.html.erb
sa\hfivdgzbfhsfb

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteudo:</strong>
  <%= @post.conteudo %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.User.nome.capitalize %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>